"""
Patient Flow Prediction Module for Hospital Operations Agent.

This module provides sophisticated forecasting capabilities for hospital patient flow,
including emergency department arrivals, inpatient admissions, bed occupancy rates,
and discharge patterns. It uses multiple prediction models (statistical, ML, deep learning)
to provide accurate forecasts for operational planning.

The module integrates with hospital data sources, performs feature engineering,
and generates predictions that help hospital administrators optimize resource allocation,
reduce wait times, and improve patient care delivery.
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Tuple, Optional, Any, Union
from enum import Enum
import logging
import json
import pickle
from pathlib import Path

# Machine Learning and Deep Learning Imports
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

# Time Series Specific Imports
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

# Configure logging for production monitoring
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/flow_predictor.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class PredictionHorizon(Enum):
    """
    Enumeration defining prediction time horizons for different operational needs.
    
    ShortTerm: Used for immediate operational decisions like staffing adjustments
    MediumTerm: Used for shift planning and resource allocation
    LongTerm: Used for strategic planning and budget forecasting
    """
    SHORT_TERM = "short_term"      # Next 1-6 hours
    MEDIUM_TERM = "medium_term"     # Next 24-48 hours
    LONG_TERM = "long_term"         # Next 7-30 days


class FlowType(Enum):
    """
    Types of patient flow that can be predicted by the system.
    Each type corresponds to a different operational aspect of hospital management.
    """
    ED_ARRIVALS = "ed_arrivals"                 # Emergency department arrivals
    INPATIENT_ADMISSIONS = "inpatient_admissions" # New inpatient admissions
    ICU_OCCUPANCY = "icu_occupancy"              # ICU bed utilization
    SURGICAL_VOLUME = "surgical_volume"          # Scheduled surgeries
    DISCHARGES = "discharges"                    # Patient discharges
    TRANSFERS = "transfers"                       # Patient transfers between units
    OUTPATIENT_VISITS = "outpatient_visits"       # Clinic appointments


class PredictionResult:
    """
    Data class encapsulating the complete prediction result with metadata.
    
    This class provides a standardized format for all predictions generated by
    the system, including confidence intervals, contributing factors, and
    model performance metrics.
    
    Attributes:
        flow_type: Type of flow being predicted
        horizon: Prediction time horizon
        timestamps: List of prediction timestamps
        values: Predicted values corresponding to timestamps
        lower_bound: Lower bound of prediction interval (uncertainty)
        upper_bound: Upper bound of prediction interval (uncertainty)
        confidence_score: Overall confidence score (0-1)
        model_used: Name of the model that generated the prediction
        features_importance: Dictionary of feature importance scores
        metadata: Additional prediction metadata
        generated_at: Timestamp when prediction was generated
    """
    
    def __init__(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        timestamps: List[datetime],
        values: List[float],
        lower_bound: Optional[List[float]] = None,
        upper_bound: Optional[List[float]] = None,
        confidence_score: float = 0.0,
        model_used: str = "unknown",
        features_importance: Optional[Dict[str, float]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ):
        self.flow_type = flow_type
        self.horizon = horizon
        self.timestamps = timestamps
        self.values = values
        self.lower_bound = lower_bound or [v * 0.9 for v in values]  # Default 10% lower bound
        self.upper_bound = upper_bound or [v * 1.1 for v in values]  # Default 10% upper bound
        self.confidence_score = confidence_score
        self.model_used = model_used
        self.features_importance = features_importance or {}
        self.metadata = metadata or {}
        self.generated_at = datetime.now()
        
    def to_dict(self) -> Dict[str, Any]:
        """Convert prediction result to dictionary for serialization."""
        return {
            "flow_type": self.flow_type.value,
            "horizon": self.horizon.value,
            "timestamps": [ts.isoformat() for ts in self.timestamps],
            "values": self.values,
            "lower_bound": self.lower_bound,
            "upper_bound": self.upper_bound,
            "confidence_score": self.confidence_score,
            "model_used": self.model_used,
            "features_importance": self.features_importance,
            "metadata": self.metadata,
            "generated_at": self.generated_at.isoformat()
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'PredictionResult':
        """Create prediction result from dictionary."""
        return cls(
            flow_type=FlowType(data["flow_type"]),
            horizon=PredictionHorizon(data["horizon"]),
            timestamps=[datetime.fromisoformat(ts) for ts in data["timestamps"]],
            values=data["values"],
            lower_bound=data.get("lower_bound"),
            upper_bound=data.get("upper_bound"),
            confidence_score=data.get("confidence_score", 0.0),
            model_used=data.get("model_used", "unknown"),
            features_importance=data.get("features_importance"),
            metadata=data.get("metadata")
        )


class LSTMPredictor(nn.Module):
    """
    LSTM-based neural network for time series prediction.
    
    This model captures long-term dependencies in sequential patient flow data
    using stacked LSTM layers with dropout for regularization.
    
    Architecture:
        - Input layer: Sequence of historical values
        - LSTM layers: 2 layers with configurable hidden size
        - Dropout: Prevents overfitting
        - Fully connected: Maps LSTM output to predictions
        
    Args:
        input_size: Number of input features (typically 1 for univariate)
        hidden_size: Number of LSTM hidden units
        num_layers: Number of stacked LSTM layers
        output_size: Number of output values to predict
        dropout: Dropout probability for regularization
    """
    
    def __init__(
        self,
        input_size: int = 1,
        hidden_size: int = 64,
        num_layers: int = 2,
        output_size: int = 1,
        dropout: float = 0.2
    ):
        super(LSTMPredictor, self).__init__()
        
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        # LSTM layers for sequence modeling
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0
        )
        
        # Dropout layer for regularization
        self.dropout = nn.Dropout(dropout)
        
        # Fully connected output layer
        self.fc = nn.Linear(hidden_size, output_size)
        
        # Initialize weights using Xavier initialization for better convergence
        self._init_weights()
        
    def _init_weights(self):
        """Initialize model weights using Xavier initialization."""
        for name, param in self.named_parameters():
            if 'weight' in name:
                nn.init.xavier_uniform_(param)
            elif 'bias' in name:
                nn.init.zeros_(param)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass through the network.
        
        Args:
            x: Input tensor of shape (batch_size, sequence_length, input_size)
            
        Returns:
            Output tensor of shape (batch_size, output_size)
        """
        # Initialize hidden state with zeros
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))
        
        # Take the output from the last time step
        out = out[:, -1, :]
        
        # Apply dropout
        out = self.dropout(out)
        
        # Pass through fully connected layer
        out = self.fc(out)
        
        return out


class TemporalConvolutionalNetwork(nn.Module):
    """
    Temporal Convolutional Network for time series prediction.
    
    TCNs use dilated causal convolutions to capture long-range patterns
    efficiently with parallel processing capabilities.
    
    Architecture:
        - Multiple convolutional layers with increasing dilation
        - Residual connections for gradient flow
        - Causal padding to maintain temporal order
        
    Args:
        input_size: Number of input channels
        num_channels: List of channel sizes for each layer
        kernel_size: Size of convolutional kernels
        dropout: Dropout probability
    """
    
    def __init__(
        self,
        input_size: int = 1,
        num_channels: List[int] = [32, 64, 64],
        kernel_size: int = 3,
        dropout: float = 0.2
    ):
        super(TemporalConvolutionalNetwork, self).__init__()
        
        layers = []
        num_levels = len(num_channels)
        
        for i in range(num_levels):
            dilation = 2 ** i  # Exponential dilation for larger receptive field
            in_channels = input_size if i == 0 else num_channels[i-1]
            out_channels = num_channels[i]
            
            # Create causal convolutional block
            layers += [
                CausalConv1d(in_channels, out_channels, kernel_size, dilation),
                nn.ReLU(),
                nn.Dropout(dropout)
            ]
        
        self.network = nn.Sequential(*layers)
        self.final_conv = nn.Conv1d(num_channels[-1], 1, kernel_size=1)
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass through TCN.
        
        Args:
            x: Input tensor of shape (batch_size, channels, sequence_length)
            
        Returns:
            Output tensor of shape (batch_size, 1)
        """
        # Apply temporal convolutional layers
        out = self.network(x)
        
        # Global average pooling across time dimension
        out = out.mean(dim=-1)
        
        # Final convolution to produce prediction
        out = self.final_conv(out.unsqueeze(-1)).squeeze(-1)
        
        return out


class CausalConv1d(nn.Module):
    """
    1D Causal Convolution for temporal models.
    
    Ensures that predictions at time t depend only on inputs up to time t,
    maintaining temporal causality essential for time series forecasting.
    """
    
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        dilation: int = 1
    ):
        super(CausalConv1d, self).__init__()
        
        self.padding = (kernel_size - 1) * dilation
        self.conv = nn.Conv1d(
            in_channels,
            out_channels,
            kernel_size,
            padding=self.padding,
            dilation=dilation
        )
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Apply convolution and remove the padding to maintain causality
        return self.conv(x)[:, :, :-self.padding] if self.padding > 0 else self.conv(x)


class FeatureExtractor:
    """
    Extracts and engineers features from raw hospital data for prediction models.
    
    This class handles the transformation of raw timestamp and patient data into
    meaningful features that improve prediction accuracy.
    
    Features extracted:
        - Temporal features: hour, day, month, day of week, holidays
        - Cyclical features: sin/cos encoding of time
        - Lag features: previous values for autoregressive modeling
        - Rolling statistics: moving averages, standard deviations
        - External factors: weather, events, seasonal patterns
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.scaler = StandardScaler()
        self.label_encoders = {}
        self.is_fitted = False
        
    def extract_temporal_features(self, timestamps: List[datetime]) -> pd.DataFrame:
        """
        Extract temporal features from datetime objects.
        
        Args:
            timestamps: List of datetime objects
            
        Returns:
            DataFrame with temporal features
        """
        df = pd.DataFrame({'timestamp': timestamps})
        
        # Basic temporal features
        df['hour'] = df['timestamp'].dt.hour
        df['day'] = df['timestamp'].dt.day
        df['month'] = df['timestamp'].dt.month
        df['year'] = df['timestamp'].dt.year
        df['day_of_week'] = df['timestamp'].dt.dayofweek
        df['day_of_year'] = df['timestamp'].dt.dayofyear
        df['week_of_year'] = df['timestamp'].dt.isocalendar().week.astype(int)
        df['quarter'] = df['timestamp'].dt.quarter
        df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)
        
        # Cyclical encoding for periodic features
        # This preserves the circular nature of time (e.g., hour 23 is close to hour 0)
        df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
        df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
        df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
        df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)
        df['day_of_week_sin'] = np.sin(2 * np.pi * df['day_of_week'] / 7)
        df['day_of_week_cos'] = np.cos(2 * np.pi * df['day_of_week'] / 7)
        
        # US Federal Holidays (simplified - in production use holiday library)
        holidays = self._get_holiday_dates()
        df['is_holiday'] = df['timestamp'].dt.date.isin(holidays).astype(int)
        
        # Time since midnight in hours (continuous)
        df['time_decimal'] = df['hour'] + df['timestamp'].dt.minute / 60
        
        return df
    
    def _get_holiday_dates(self, years: Optional[List[int]] = None) -> set:
        """
        Get US federal holiday dates for given years.
        Simplified implementation - use holidays library in production.
        """
        if years is None:
            years = [datetime.now().year - 1, datetime.now().year, datetime.now().year + 1]
        
        holidays = set()
        # This is a simplified list - in production, use the 'holidays' package
        for year in years:
            holidays.add(date(year, 1, 1))   # New Year's Day
            holidays.add(date(year, 7, 4))   # Independence Day
            holidays.add(date(year, 12, 25)) # Christmas Day
            # Add more holidays as needed
        
        return holidays
    
    def create_lag_features(
        self,
        series: pd.Series,
        lags: List[int] = [1, 2, 3, 6, 12, 24, 48]
    ) -> pd.DataFrame:
        """
        Create lag features for autoregressive modeling.
        
        Args:
            series: Time series data
            lags: List of lag periods (in hours for hourly data)
            
        Returns:
            DataFrame with lag features
        """
        df = pd.DataFrame(index=series.index)
        
        for lag in lags:
            df[f'lag_{lag}'] = series.shift(lag)
        
        return df
    
    def create_rolling_features(
        self,
        series: pd.Series,
        windows: List[int] = [6, 12, 24, 168]  # 6h, 12h, 24h, 1 week
    ) -> pd.DataFrame:
        """
        Create rolling statistics features.
        
        Args:
            series: Time series data
            windows: List of window sizes (in hours)
            
        Returns:
            DataFrame with rolling features
        """
        df = pd.DataFrame(index=series.index)
        
        for window in windows:
            rolling = series.rolling(window=window, min_periods=1)
            df[f'rolling_mean_{window}'] = rolling.mean()
            df[f'rolling_std_{window}'] = rolling.std()
            df[f'rolling_min_{window}'] = rolling.min()
            df[f'rolling_max_{window}'] = rolling.max()
            df[f'rolling_skew_{window}'] = rolling.skew()
        
        return df
    
    def extract_external_features(
        self,
        timestamps: List[datetime],
        location: Optional[str] = None
    ) -> pd.DataFrame:
        """
        Extract external features like weather, events, etc.
        
        In production, this would call weather APIs and event databases.
        """
        df = pd.DataFrame(index=range(len(timestamps)))
        
        # Placeholder for external features
        # In production, you would:
        # 1. Call weather API for temperature, precipitation, etc.
        # 2. Fetch local events and holidays
        # 3. Get traffic data if relevant
        # 4. Include epidemiological data during outbreaks
        
        df['temperature'] = np.random.normal(20, 5, len(timestamps))  # Placeholder
        df['precipitation'] = np.random.exponential(0.1, len(timestamps))  # Placeholder
        
        return df
    
    def fit_transform(
        self,
        timestamps: List[datetime],
        values: Optional[List[float]] = None,
        fit_scaler: bool = True
    ) -> pd.DataFrame:
        """
        Fit feature extractor and transform data.
        
        Args:
            timestamps: List of datetime objects
            values: Optional target values for lag feature creation
            fit_scaler: Whether to fit the scaler (True for training, False for inference)
            
        Returns:
            DataFrame with all features
        """
        # Extract temporal features
        features = self.extract_temporal_features(timestamps)
        
        # Add lag and rolling features if values are provided
        if values is not None:
            series = pd.Series(values, index=range(len(values)))
            
            lag_features = self.create_lag_features(series)
            rolling_features = self.create_rolling_features(series)
            
            features = pd.concat([features, lag_features, rolling_features], axis=1)
        
        # Add external features
        external_features = self.extract_external_features(timestamps)
        features = pd.concat([features, external_features], axis=1)
        
        # Handle missing values
        features = features.fillna(method='bfill').fillna(method='ffill').fillna(0)
        
        # Scale features
        if fit_scaler:
            self.scaler.fit(features)
            self.is_fitted = True
        
        if self.is_fitted:
            scaled_values = self.scaler.transform(features)
            features = pd.DataFrame(scaled_values, columns=features.columns, index=features.index)
        
        return features


class EnsemblePredictor:
    """
    Ensemble predictor combining multiple models for robust forecasting.
    
    This class implements ensemble methods (bagging, boosting, stacking) to
    combine predictions from multiple models, reducing variance and improving
    accuracy through collective intelligence.
    
    Methods:
        - Bagging: Averaging predictions from multiple models
        - Weighted ensemble: Weighted average based on model performance
        - Stacking: Meta-model learning from base model predictions
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.models = []
        self.weights = []
        self.meta_model = None
        self.is_fitted = False
        
    def add_model(
        self,
        model: Any,
        weight: float = 1.0,
        model_type: str = "base"
    ):
        """
        Add a model to the ensemble.
        
        Args:
            model: The model instance
            weight: Weight for weighted ensemble
            model_type: 'base' for base models or 'meta' for stacking meta-model
        """
        if model_type == "meta":
            self.meta_model = model
        else:
            self.models.append(model)
            self.weights.append(weight)
    
    def fit(
        self,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: Optional[np.ndarray] = None,
        y_val: Optional[np.ndarray] = None
    ):
        """
        Fit all models in the ensemble.
        
        For stacking, uses validation predictions to train meta-model.
        """
        # Fit base models
        for model in self.models:
            model.fit(X_train, y_train)
        
        # Prepare stacking if meta-model exists
        if self.meta_model is not None and X_val is not None and y_val is not None:
            # Generate base model predictions on validation set
            val_predictions = []
            for model in self.models:
                pred = model.predict(X_val)
                val_predictions.append(pred)
            
            # Stack predictions as features for meta-model
            X_meta = np.column_stack(val_predictions)
            
            # Fit meta-model
            self.meta_model.fit(X_meta, y_val)
        
        self.is_fitted = True
    
    def predict(
        self,
        X: np.ndarray,
        method: str = "weighted"
    ) -> np.ndarray:
        """
        Generate ensemble predictions.
        
        Args:
            X: Input features
            method: 'bagging', 'weighted', or 'stacking'
            
        Returns:
            Ensemble predictions
        """
        if not self.is_fitted:
            raise ValueError("Model must be fitted before prediction")
        
        if method == "bagging":
            # Simple average of all models
            predictions = np.array([model.predict(X) for model in self.models])
            return np.mean(predictions, axis=0)
        
        elif method == "weighted":
            # Weighted average based on model weights
            predictions = np.array([model.predict(X) for model in self.models])
            weights = np.array(self.weights) / sum(self.weights)
            return np.sum(predictions * weights.reshape(-1, 1), axis=0)
        
        elif method == "stacking" and self.meta_model is not None:
            # Stacking: use meta-model on base model predictions
            base_predictions = []
            for model in self.models:
                pred = model.predict(X)
                base_predictions.append(pred)
            
            X_meta = np.column_stack(base_predictions)
            return self.meta_model.predict(X_meta)
        
        else:
            raise ValueError(f"Unknown ensemble method: {method}")


class FlowPredictor:
    """
    Main predictor class for hospital patient flow forecasting.
    
    This is the core class that orchestrates all prediction activities:
        - Data collection and preprocessing
        - Feature engineering
        - Model training and selection
        - Prediction generation
        - Uncertainty quantification
        - Performance monitoring
        
    The class supports multiple prediction horizons and flow types,
    automatically selecting the best model for each scenario.
    """
    
    def __init__(
        self,
        model_save_path: str = "models/flow_predictor/",
        config: Optional[Dict[str, Any]] = None
    ):
        """
        Initialize the Flow Predictor.
        
        Args:
            model_save_path: Directory path for saving trained models
            config: Configuration dictionary with model parameters
        """
        self.model_save_path = Path(model_save_path)
        self.model_save_path.mkdir(parents=True, exist_ok=True)
        
        self.config = config or self._get_default_config()
        self.feature_extractor = FeatureExtractor(self.config.get("feature_config"))
        
        # Dictionary to store models for each flow type and horizon
        self.models: Dict[str, Dict[str, Any]] = {}
        
        # Performance tracking
        self.performance_history: List[Dict[str, Any]] = []
        
        # Load existing models if available
        self._load_models()
        
        logger.info("FlowPredictor initialized successfully")
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration for the predictor."""
        return {
            "feature_config": {
                "use_lag_features": True,
                "lags": [1, 2, 3, 6, 12, 24, 48, 72, 168],
                "use_rolling_features": True,
                "rolling_windows": [6, 12, 24, 48, 168],
                "use_external_features": True
            },
            "model_config": {
                "lstm": {
                    "hidden_size": 64,
                    "num_layers": 2,
                    "dropout": 0.2,
                    "learning_rate": 0.001,
                    "batch_size": 32,
                    "epochs": 100,
                    "early_stopping_patience": 10
                },
                "tcn": {
                    "num_channels": [32, 64, 64],
                    "kernel_size": 3,
                    "dropout": 0.2,
                    "learning_rate": 0.001
                },
                "random_forest": {
                    "n_estimators": 100,
                    "max_depth": 20,
                    "min_samples_split": 5,
                    "min_samples_leaf": 2
                },
                "gradient_boosting": {
                    "n_estimators": 100,
                    "learning_rate": 0.1,
                    "max_depth": 5,
                    "subsample": 0.8
                }
            },
            "ensemble_config": {
                "use_ensemble": True,
                "ensemble_method": "weighted",
                "cross_validation_folds": 5
            },
            "prediction_config": {
                "confidence_interval": 0.95,
                "min_training_samples": 100,
                "retrain_frequency_hours": 24,
                "max_forecast_horizon": 720  # 30 days in hours
            },
            "device": "cuda" if torch.cuda.is_available() else "cpu"
        }
    
    def _load_models(self):
        """Load pre-trained models from disk."""
        try:
            model_files = list(self.model_save_path.glob("*.pkl"))
            for model_file in model_files:
                with open(model_file, 'rb') as f:
                    model_data = pickle.load(f)
                    key = model_file.stem
                    self.models[key] = model_data
            logger.info(f"Loaded {len(model_files)} existing models")
        except Exception as e:
            logger.warning(f"Could not load existing models: {str(e)}")
    
    def _save_model(self, model_key: str):
        """Save a trained model to disk."""
        if model_key in self.models:
            model_path = self.model_save_path / f"{model_key}.pkl"
            with open(model_path, 'wb') as f:
                pickle.dump(self.models[model_key], f)
            logger.info(f"Saved model to {model_path}")
    
    def prepare_training_data(
        self,
        historical_data: pd.DataFrame,
        flow_type: FlowType,
        target_column: str,
        sequence_length: int = 24
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        """
        Prepare data for model training with proper train/validation split.
        
        Args:
            historical_data: DataFrame with timestamp and target columns
            flow_type: Type of flow being predicted
            target_column: Name of column containing target values
            sequence_length: Length of input sequences for time series models
            
        Returns:
            Tuple of (X_train, y_train, X_val, y_val)
        """
        logger.info(f"Preparing training data for {flow_type.value}")
        
        # Ensure data is sorted by time
        if 'timestamp' in historical_data.columns:
            historical_data = historical_data.sort_values('timestamp')
        
        # Extract features
        timestamps = historical_data['timestamp'].tolist()
        values = historical_data[target_column].values
        
        features = self.feature_extractor.fit_transform(
            timestamps,
            values,
            fit_scaler=True
        )
        
        # Create sequences for time series models
        X, y = [], []
        for i in range(len(features) - sequence_length):
            X.append(features.iloc[i:i+sequence_length].values)
            y.append(values[i+sequence_length])
        
        X = np.array(X)
        y = np.array(y)
        
        # Split into train and validation (time-based split)
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X[:split_idx], X[split_idx:]
        y_train, y_val = y[:split_idx], y[split_idx:]
        
        logger.info(f"Training data shape: {X_train.shape}, Validation shape: {X_val.shape}")
        
        return X_train, y_train, X_val, y_val
    
    def train_lstm_model(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: np.ndarray,
        y_val: np.ndarray
    ) -> LSTMPredictor:
        """
        Train an LSTM model for time series prediction.
        
        Args:
            flow_type: Type of flow being predicted
            horizon: Prediction horizon
            X_train, y_train: Training data
            X_val, y_val: Validation data
            
        Returns:
            Trained LSTM model
        """
        logger.info(f"Training LSTM model for {flow_type.value} - {horizon.value}")
        
        # Get model configuration
        lstm_config = self.config["model_config"]["lstm"]
        
        # Convert data to PyTorch tensors
        X_train_tensor = torch.FloatTensor(X_train).to(self.config["device"])
        y_train_tensor = torch.FloatTensor(y_train).to(self.config["device"])
        X_val_tensor = torch.FloatTensor(X_val).to(self.config["device"])
        y_val_tensor = torch.FloatTensor(y_val).to(self.config["device"])
        
        # Create data loaders
        train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
        train_loader = DataLoader(
            train_dataset,
            batch_size=lstm_config["batch_size"],
            shuffle=True
        )
        
        # Initialize model
        model = LSTMPredictor(
            input_size=X_train.shape[2],
            hidden_size=lstm_config["hidden_size"],
            num_layers=lstm_config["num_layers"],
            output_size=1,
            dropout=lstm_config["dropout"]
        ).to(self.config["device"])
        
        # Loss function and optimizer
        criterion = nn.MSELoss()
        optimizer = optim.Adam(model.parameters(), lr=lstm_config["learning_rate"])
        
        # Learning rate scheduler
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode='min',
            factor=0.5,
            patience=5,
            verbose=True
        )
        
        # Training loop
        best_val_loss = float('inf')
        patience_counter = 0
        
        for epoch in range(lstm_config["epochs"]):
            # Training phase
            model.train()
            train_loss = 0.0
            
            for batch_X, batch_y in train_loader:
                optimizer.zero_grad()
                
                # Forward pass
                outputs = model(batch_X).squeeze()
                loss = criterion(outputs, batch_y)
                
                # Backward pass
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()
                
                train_loss += loss.item()
            
            avg_train_loss = train_loss / len(train_loader)
            
            # Validation phase
            model.eval()
            with torch.no_grad():
                val_outputs = model(X_val_tensor).squeeze()
                val_loss = criterion(val_outputs, y_val_tensor).item()
            
            # Update learning rate
            scheduler.step(val_loss)
            
            # Early stopping check
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_counter = 0
                # Save best model
                self.models[f"{flow_type.value}_{horizon.value}_lstm"] = {
                    "model": model.state_dict(),
                    "val_loss": val_loss,
                    "epoch": epoch
                }
            else:
                patience_counter += 1
                if patience_counter >= lstm_config["early_stopping_patience"]:
                    logger.info(f"Early stopping at epoch {epoch}")
                    break
            
            if epoch % 10 == 0:
                logger.info(f"Epoch {epoch}: Train Loss = {avg_train_loss:.4f}, Val Loss = {val_loss:.4f}")
        
        # Load best model
        best_model_state = self.models[f"{flow_type.value}_{horizon.value}_lstm"]["model"]
        model.load_state_dict(best_model_state)
        
        return model
    
    def train_ml_models(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        X_train: np.ndarray,
        y_train: np.ndarray
    ) -> Dict[str, Any]:
        """
        Train traditional machine learning models (Random Forest, Gradient Boosting).
        
        Args:
            flow_type: Type of flow being predicted
            horizon: Prediction horizon
            X_train, y_train: Training data
            
        Returns:
            Dictionary of trained models
        """
        logger.info(f"Training ML models for {flow_type.value} - {horizon.value}")
        
        # Flatten the sequence dimension for ML models
        n_samples = X_train.shape[0]
        X_train_flat = X_train.reshape(n_samples, -1)
        
        # Get model configurations
        rf_config = self.config["model_config"]["random_forest"]
        gb_config = self.config["model_config"]["gradient_boosting"]
        
        # Train Random Forest
        rf_model = RandomForestRegressor(
            n_estimators=rf_config["n_estimators"],
            max_depth=rf_config["max_depth"],
            min_samples_split=rf_config["min_samples_split"],
            min_samples_leaf=rf_config["min_samples_leaf"],
            random_state=42,
            n_jobs=-1
        )
        rf_model.fit(X_train_flat, y_train)
        
        # Train Gradient Boosting
        gb_model = GradientBoostingRegressor(
            n_estimators=gb_config["n_estimators"],
            learning_rate=gb_config["learning_rate"],
            max_depth=gb_config["max_depth"],
            subsample=gb_config["subsample"],
            random_state=42
        )
        gb_model.fit(X_train_flat, y_train)
        
        # Calculate feature importance
        feature_importance = {
            "random_forest": dict(zip(
                [f"feature_{i}" for i in range(X_train_flat.shape[1])],
                rf_model.feature_importances_
            )),
            "gradient_boosting": dict(zip(
                [f"feature_{i}" for i in range(X_train_flat.shape[1])],
                gb_model.feature_importances_
            ))
        }
        
        models = {
            "random_forest": rf_model,
            "gradient_boosting": gb_model,
            "feature_importance": feature_importance
        }
        
        # Save models
        self.models[f"{flow_type.value}_{horizon.value}_ml"] = models
        
        return models
    
    def train_ensemble(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: np.ndarray,
        y_val: np.ndarray
    ) -> EnsemblePredictor:
        """
        Train an ensemble model combining multiple predictors.
        
        Args:
            flow_type: Type of flow being predicted
            horizon: Prediction horizon
            X_train, y_train: Training data
            X_val, y_val: Validation data
            
        Returns:
            Trained ensemble predictor
        """
        logger.info(f"Training ensemble model for {flow_type.value} - {horizon.value}")
        
        # Flatten sequences for ensemble
        n_train = X_train.shape[0]
        n_val = X_val.shape[0]
        X_train_flat = X_train.reshape(n_train, -1)
        X_val_flat = X_val.reshape(n_val, -1)
        
        # Create ensemble
        ensemble = EnsemblePredictor(self.config.get("ensemble_config"))
        
        # Add base models
        rf_config = self.config["model_config"]["random_forest"]
        gb_config = self.config["model_config"]["gradient_boosting"]
        
        # Random Forest with different hyperparameters
        for i in range(3):
            rf = RandomForestRegressor(
                n_estimators=rf_config["n_estimators"] * (i + 1),
                max_depth=rf_config["max_depth"] + i * 5,
                random_state=42 + i,
                n_jobs=-1
            )
            ensemble.add_model(rf, weight=1.0, model_type="base")
        
        # Gradient Boosting with different learning rates
        for lr in [0.05, 0.1, 0.15]:
            gb = GradientBoostingRegressor(
                n_estimators=gb_config["n_estimators"],
                learning_rate=lr,
                max_depth=gb_config["max_depth"],
                random_state=42
            )
            ensemble.add_model(gb, weight=1.0, model_type="base")
        
        # Add meta-model for stacking
        meta_model = GradientBoostingRegressor(
            n_estimators=50,
            learning_rate=0.1,
            max_depth=3,
            random_state=42
        )
        ensemble.add_model(meta_model, model_type="meta")
        
        # Fit ensemble
        ensemble.fit(X_train_flat, y_train, X_val_flat, y_val)
        
        # Save ensemble
        self.models[f"{flow_type.value}_{horizon.value}_ensemble"] = {
            "ensemble": ensemble,
            "config": self.config["ensemble_config"]
        }
        
        return ensemble
    
    def train_all_models(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        historical_data: pd.DataFrame,
        target_column: str
    ):
        """
        Train all available models for a specific flow type and horizon.
        
        Args:
            flow_type: Type of flow to predict
            horizon: Prediction horizon
            historical_data: Historical data for training
            target_column: Column containing target values
        """
        logger.info(f"Training all models for {flow_type.value} - {horizon.value}")
        
        # Prepare data
        sequence_length = self._get_sequence_length(horizon)
        X_train, y_train, X_val, y_val = self.prepare_training_data(
            historical_data,
            flow_type,
            target_column,
            sequence_length
        )
        
        # Train LSTM if using deep learning
        if self.config.get("use_deep_learning", True):
            try:
                lstm_model = self.train_lstm_model(
                    flow_type, horizon, X_train, y_train, X_val, y_val
                )
                logger.info(f"LSTM training completed for {flow_type.value}")
            except Exception as e:
                logger.error(f"LSTM training failed: {str(e)}")
        
        # Train ML models
        try:
            ml_models = self.train_ml_models(
                flow_type, horizon, X_train, y_train
            )
            logger.info(f"ML models training completed for {flow_type.value}")
        except Exception as e:
            logger.error(f"ML models training failed: {str(e)}")
        
        # Train ensemble if configured
        if self.config["ensemble_config"]["use_ensemble"]:
            try:
                ensemble = self.train_ensemble(
                    flow_type, horizon, X_train, y_train, X_val, y_val
                )
                logger.info(f"Ensemble training completed for {flow_type.value}")
            except Exception as e:
                logger.error(f"Ensemble training failed: {str(e)}")
        
        # Save models
        self._save_model(f"{flow_type.value}_{horizon.value}_all")
        logger.info(f"All models saved for {flow_type.value} - {horizon.value}")
    
    def _get_sequence_length(self, horizon: PredictionHorizon) -> int:
        """Determine appropriate sequence length based on prediction horizon."""
        if horizon == PredictionHorizon.SHORT_TERM:
            return 12  # Last 12 hours for short-term predictions
        elif horizon == PredictionHorizon.MEDIUM_TERM:
            return 48  # Last 48 hours for medium-term predictions
        else:  # LONG_TERM
            return 168  # Last 7 days for long-term predictions
    
    def _select_best_model(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        X_val: np.ndarray,
        y_val: np.ndarray
    ) -> Tuple[str, Any]:
        """
        Select the best performing model for a specific flow type and horizon.
        
        Evaluates all available models on validation data and selects the one
        with the lowest error.
        
        Args:
            flow_type: Type of flow
            horizon: Prediction horizon
            X_val, y_val: Validation data
            
        Returns:
            Tuple of (model_name, model_object)
        """
        model_key_base = f"{flow_type.value}_{horizon.value}"
        best_model = None
        best_model_name = None
        best_score = float('inf')
        
        # Flatten validation data for ML models
        n_val = X_val.shape[0]
        X_val_flat = X_val.reshape(n_val, -1)
        
        # Check LSTM model
        lstm_key = f"{model_key_base}_lstm"
        if lstm_key in self.models:
            try:
                model_data = self.models[lstm_key]
                # Recreate model and load weights
                lstm_config = self.config["model_config"]["lstm"]
                model = LSTMPredictor(
                    input_size=X_val.shape[2],
                    hidden_size=lstm_config["hidden_size"],
                    num_layers=lstm_config["num_layers"],
                    output_size=1
                ).to(self.config["device"])
                model.load_state_dict(model_data["model"])
                
                # Evaluate
                model.eval()
                with torch.no_grad():
                    X_val_tensor = torch.FloatTensor(X_val).to(self.config["device"])
                    predictions = model(X_val_tensor).squeeze().cpu().numpy()
                
                mae = mean_absolute_error(y_val, predictions)
                
                if mae < best_score:
                    best_score = mae
                    best_model = model
                    best_model_name = "lstm"
            except Exception as e:
                logger.warning(f"Could not evaluate LSTM model: {str(e)}")
        
        # Check ML models
        ml_key = f"{model_key_base}_ml"
        if ml_key in self.models:
            ml_models = self.models[ml_key]
            
            for model_name in ["random_forest", "gradient_boosting"]:
                if model_name in ml_models:
                    try:
                        model = ml_models[model_name]
                        predictions = model.predict(X_val_flat)
                        mae = mean_absolute_error(y_val, predictions)
                        
                        if mae < best_score:
                            best_score = mae
                            best_model = model
                            best_model_name = model_name
                    except Exception as e:
                        logger.warning(f"Could not evaluate {model_name}: {str(e)}")
        
        # Check ensemble
        ensemble_key = f"{model_key_base}_ensemble"
        if ensemble_key in self.models and self.config["ensemble_config"]["use_ensemble"]:
            try:
                ensemble_data = self.models[ensemble_key]
                ensemble = ensemble_data["ensemble"]
                predictions = ensemble.predict(X_val_flat)
                mae = mean_absolute_error(y_val, predictions)
                
                if mae < best_score:
                    best_score = mae
                    best_model = ensemble
                    best_model_name = "ensemble"
            except Exception as e:
                logger.warning(f"Could not evaluate ensemble: {str(e)}")
        
        if best_model is None:
            raise ValueError(f"No trained models found for {flow_type.value} - {horizon.value}")
        
        logger.info(f"Selected {best_model_name} model for {flow_type.value} - {horizon.value} with MAE={best_score:.2f}")
        
        # Store performance
        self.performance_history.append({
            "flow_type": flow_type.value,
            "horizon": horizon.value,
            "selected_model": best_model_name,
            "mae": best_score,
            "timestamp": datetime.now().isoformat()
        })
        
        return best_model_name, best_model
    
    async def predict(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        current_data: pd.DataFrame,
        target_column: str,
        forecast_steps: int
    ) -> PredictionResult:
        """
        Generate predictions for a specific flow type and horizon.
        
        This is the main prediction method called by external systems.
        
        Args:
            flow_type: Type of flow to predict
            horizon: Prediction horizon
            current_data: Recent historical data for prediction
            target_column: Column containing target values
            forecast_steps: Number of steps to forecast ahead
            
        Returns:
            PredictionResult object containing predictions and metadata
        """
        logger.info(f"Generating predictions for {flow_type.value} - {horizon.value}")
        
        # Prepare input data
        timestamps = current_data['timestamp'].tolist()[-forecast_steps:]
        
        # Extract features for prediction
        features = self.feature_extractor.fit_transform(
            timestamps,
            fit_scaler=False  # Use previously fitted scaler
        )
        
        # Create sequences
        sequence_length = self._get_sequence_length(horizon)
        if len(features) < sequence_length:
            raise ValueError(f"Insufficient data: need {sequence_length} timestamps, got {len(features)}")
        
        # Get last sequence for prediction
        last_sequence = features.iloc[-sequence_length:].values
        last_sequence = last_sequence.reshape(1, sequence_length, -1)
        
        # Select best model
        X_val = last_sequence  # Using current data as validation for selection
        y_val_dummy = np.zeros(1)  # Dummy target for model selection
        
        model_name, model = self._select_best_model(
            flow_type,
            horizon,
            X_val,
            y_val_dummy
        )
        
        # Generate predictions
        predictions = []
        
        if model_name in ["lstm"]:
            # Deep learning model
            model.eval()
            with torch.no_grad():
                X_tensor = torch.FloatTensor(last_sequence).to(self.config["device"])
                pred = model(X_tensor).squeeze().cpu().numpy()
                predictions = [float(pred)] * forecast_steps
                
        elif model_name in ["random_forest", "gradient_boosting"]:
            # Traditional ML model
            last_sequence_flat = last_sequence.reshape(1, -1)
            pred = model.predict(last_sequence_flat)[0]
            predictions = [float(pred)] * forecast_steps
            
        elif model_name == "ensemble":
            # Ensemble model
            last_sequence_flat = last_sequence.reshape(1, -1)
            pred = model.predict(last_sequence_flat)[0]
            predictions = [float(pred)] * forecast_steps
        
        # Calculate confidence intervals
        # In production, this would use bootstrap or Monte Carlo dropout
        std_dev = np.std(predictions) if len(predictions) > 1 else 0.1 * predictions[0]
        lower_bound = [p - 1.96 * std_dev for p in predictions]
        upper_bound = [p + 1.96 * std_dev for p in predictions]
        
        # Calculate confidence score based on model performance
        confidence_score = self._calculate_confidence_score(
            flow_type,
            horizon,
            model_name,
            predictions
        )
        
        # Get feature importance
        feature_importance = self._get_feature_importance(
            flow_type,
            horizon,
            model_name
        )
        
        # Create future timestamps
        future_timestamps = [
            timestamps[-1] + timedelta(hours=i+1)
            for i in range(forecast_steps)
        ]
        
        # Create prediction result
        result = PredictionResult(
            flow_type=flow_type,
            horizon=horizon,
            timestamps=future_timestamps,
            values=predictions,
            lower_bound=lower_bound,
            upper_bound=upper_bound,
            confidence_score=confidence_score,
            model_used=model_name,
            features_importance=feature_importance,
            metadata={
                "sequence_length": sequence_length,
                "forecast_steps": forecast_steps,
                "model_config": self.config["model_config"].get(model_name, {})
            }
        )
        
        logger.info(f"Prediction generated successfully with confidence {confidence_score:.2f}")
        
        return result
    
    def _calculate_confidence_score(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        model_name: str,
        predictions: List[float]
    ) -> float:
        """
        Calculate confidence score for predictions based on multiple factors.
        
        Factors considered:
            - Historical model performance
            - Prediction uncertainty (variance)
            - Data quality and recency
            - Seasonal pattern adherence
        """
        base_confidence = 0.8  # Start with 80% confidence
        
        # Adjust based on historical performance
        recent_performance = [
            p for p in self.performance_history[-10:]
            if p["flow_type"] == flow_type.value and p["horizon"] == horizon.value
        ]
        
        if recent_performance:
            avg_mae = np.mean([p["mae"] for p in recent_performance])
            # Normalize MAE to confidence penalty (lower MAE = higher confidence)
            mae_penalty = min(avg_mae / 100, 0.3)  # Max 30% penalty
            base_confidence -= mae_penalty
        
        # Adjust based on prediction variance
        if len(predictions) > 1:
            cv = np.std(predictions) / np.mean(predictions) if np.mean(predictions) != 0 else 0
            variance_penalty = min(cv, 0.2)  # Max 20% penalty
            base_confidence -= variance_penalty
        
        # Adjust based on horizon (longer horizon = lower confidence)
        horizon_penalties = {
            PredictionHorizon.SHORT_TERM: 0.0,
            PredictionHorizon.MEDIUM_TERM: 0.1,
            PredictionHorizon.LONG_TERM: 0.2
        }
        base_confidence -= horizon_penalties[horizon]
        
        return max(0.0, min(1.0, base_confidence))
    
    def _get_feature_importance(
        self,
        flow_type: FlowType,
        horizon: PredictionHorizon,
        model_name: str
    ) -> Dict[str, float]:
        """
        Get feature importance for the selected model.
        """
        model_key_base = f"{flow_type.value}_{horizon.value}"
        
        if model_name in ["random_forest", "gradient_boosting"]:
            ml_key = f"{model_key_base}_ml"
            if ml_key in self.models:
                importance_dict = self.models[ml_key]["feature_importance"][model_name]
                # Convert to standard format
                return {str(k): float(v) for k, v in importance_dict.items()}
        
        elif model_name == "lstm":
            # LSTM doesn't have built-in feature importance
            # Could use permutation importance here
            return {}
        
        elif model_name == "ensemble":
            # For ensemble, average importance from base models
            return {}
        
        return {}
    
    def get_performance_report(self) -> Dict[str, Any]:
        """
        Generate a comprehensive performance report for all models.
        
        Returns:
            Dictionary with performance metrics and recommendations
        """
        if not self.performance_history:
            return {"status": "No performance data available"}
        
        # Convert to DataFrame for analysis
        df = pd.DataFrame(self.performance_history)
        
        report = {
            "summary": {
                "total_predictions": len(df),
                "unique_flow_types": df['flow_type'].nunique(),
                "unique_horizons": df['horizon'].nunique(),
                "time_range": {
                    "start": df['timestamp'].min(),
                    "end": df['timestamp'].max()
                }
            },
            "performance_by_flow_type": {},
            "performance_by_horizon": {},
            "model_usage": df['selected_model'].value_counts().to_dict(),
            "recent_trends": {}
        }
        
        # Performance by flow type
        for flow_type in df['flow_type'].unique():
            flow_df = df[df['flow_type'] == flow_type]
            report["performance_by_flow_type"][flow_type] = {
                "avg_mae": float(flow_df['mae'].mean()),
                "std_mae": float(flow_df['mae'].std()),
                "min_mae": float(flow_df['mae'].min()),
                "max_mae": float(flow_df['mae'].max()),
                "predictions_count": len(flow_df)
            }
        
        # Performance by horizon
        for horizon in df['horizon'].unique():
            horizon_df = df[df['horizon'] == horizon]
            report["performance_by_horizon"][horizon] = {
                "avg_mae": float(horizon_df['mae'].mean()),
                "predictions_count": len(horizon_df)
            }
        
        # Recent trends (last 24 hours)
        last_24h = datetime.now() - timedelta(hours=24)
        recent_df = df[pd.to_datetime(df['timestamp']) > last_24h]
        if not recent_df.empty:
            report["recent_trends"] = {
                "avg_mae": float(recent_df['mae'].mean()),
                "predictions_count": len(recent_df),
                "best_model": recent_df.loc[recent_df['mae'].idxmin(), 'selected_model']
            }
        
        # Recommendations
        report["recommendations"] = self._generate_recommendations(df)
        
        return report
    
    def _generate_recommendations(self, performance_df: pd.DataFrame) -> List[str]:
        """
        Generate recommendations for model improvement based on performance.
        """
        recommendations = []
        
        # Check if any flow types need retraining
        for flow_type in performance_df['flow_type'].unique():
            flow_df = performance_df[performance_df['flow_type'] == flow_type]
            recent_mae = flow_df.tail(10)['mae'].mean() if len(flow_df) >= 10 else float('inf')
            overall_mae = flow_df['mae'].mean()
            
            if recent_mae > overall_mae * 1.2:
                recommendations.append(
                    f"Performance degradation detected for {flow_type}. Consider retraining models."
                )
        
        # Check for model diversity
        model_counts = performance_df['selected_model'].value_counts()
        if len(model_counts) < 2:
            recommendations.append(
                "Low model diversity. Consider training additional model types for better ensemble performance."
            )
        
        # Check prediction volume
        if len(performance_df) < 100:
            recommendations.append(
                "Limited prediction history. Collect more data for better performance analysis."
            )
        
        return recommendations


# Factory function for creating FlowPredictor instances
def create_flow_predictor(
    config_path: Optional[str] = None,
    model_save_path: str = "models/flow_predictor/"
) -> FlowPredictor:
    """
    Factory function to create and configure a FlowPredictor instance.
    
    Args:
        config_path: Path to configuration JSON file
        model_save_path: Path to save trained models
        
    Returns:
        Configured FlowPredictor instance
    """
    config = None
    if config_path:
        with open(config_path, 'r') as f:
            config = json.load(f)
    
    return FlowPredictor(model_save_path, config)


# Example usage and testing
if __name__ == "__main__":
    """
    Example demonstrating how to use the FlowPredictor.
    This section shows the complete workflow from data preparation
    to prediction generation.
    """
    
    # Create sample data for demonstration
    np.random.seed(42)
    
    # Generate synthetic historical data
    n_hours = 1000
    timestamps = [datetime.now() - timedelta(hours=i) for i in range(n_hours, 0, -1)]
    
    # Create pattern: daily seasonality + weekly trend + noise
    base_pattern = 50 + 20 * np.sin(2 * np.pi * np.arange(n_hours) / 24)  # Daily cycle
    weekly_pattern = 10 * np.sin(2 * np.pi * np.arange(n_hours) / (24*7))  # Weekly cycle
    noise = np.random.normal(0, 5, n_hours)
    values = base_pattern + weekly_pattern + noise
    
    # Create DataFrame
    data = pd.DataFrame({
        'timestamp': timestamps,
        'ed_arrivals': values,
        'inpatient_admissions': values * 0.3 + np.random.normal(0, 2, n_hours),
        'icu_occupancy': values * 0.1 + np.random.normal(0, 1, n_hours)
    })
    
    # Initialize predictor
    predictor = FlowPredictor()
    
    # Train models for ED arrivals
    print("Training models for ED arrivals...")
    predictor.train_all_models(
        flow_type=FlowType.ED_ARRIVALS,
        horizon=PredictionHorizon.SHORT_TERM,
        historical_data=data,
        target_column='ed_arrivals'
    )
    
    # Generate predictions
    print("\nGenerating predictions...")
    result = asyncio.run(predictor.predict(
        flow_type=FlowType.ED_ARRIVALS,
        horizon=PredictionHorizon.SHORT_TERM,
        current_data=data.tail(48),
        target_column='ed_arrivals',
        forecast_steps=12
    ))
    
    # Display results
    print(f"\nPrediction Results for {result.flow_type.value}:")
    print(f"Horizon: {result.horizon.value}")
    print(f"Model used: {result.model_used}")
    print(f"Confidence: {result.confidence_score:.2f}")
    print("\nPredictions for next 12 hours:")
    for ts, val, lower, upper in zip(
        result.timestamps[:5],  # Show first 5
        result.values[:5],
        result.lower_bound[:5],
        result.upper_bound[:5]
    ):
        print(f"{ts.strftime('%Y-%m-%d %H:%M')}: {val:.1f} "
              f"[{lower:.1f}, {upper:.1f}]")
    
    # Get performance report
    print("\nPerformance Report:")
    report = predictor.get_performance_report()
    print(json.dumps(report, indent=2))